// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPsY9Crd0e4Xkj3M3zmEM-xVQGHbDo6Ng',
    appId: '1:865249407602:web:e27e94c1cc2d4c2fdf08eb',
    messagingSenderId: '865249407602',
    projectId: 'flutter-pro-401c8',
    authDomain: 'flutter-pro-401c8.firebaseapp.com',
    databaseURL: 'https://flutter-pro-401c8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pro-401c8.firebasestorage.app',
    measurementId: 'G-W9ET5ZG4JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhFpiXwIebmXy9mhElSVGSpJG-p6Y-8e8',
    appId: '1:865249407602:android:7556b61c44d7da91df08eb',
    messagingSenderId: '865249407602',
    projectId: 'flutter-pro-401c8',
    databaseURL: 'https://flutter-pro-401c8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pro-401c8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPsY9Crd0e4Xkj3M3zmEM-xVQGHbDo6Ng',
    appId: '1:865249407602:web:57c8bf322c9c40e4df08eb',
    messagingSenderId: '865249407602',
    projectId: 'flutter-pro-401c8',
    authDomain: 'flutter-pro-401c8.firebaseapp.com',
    databaseURL: 'https://flutter-pro-401c8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pro-401c8.firebasestorage.app',
    measurementId: 'G-K1XYHM6823',
  );
}
